[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
example_program = "D1NW5bwpfVQC86ercmzqGVizp8NCuMvAVTLEK3LSCo4E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
