[workspace]
members = [
	"crates/memory_wallet",
	"crates/test_utils_insta",
	"crates/test_utils_keypairs",
	"crates/test_utils_solana",
	"crates/wasm_client_solana",
	"forks/solana-account-decoder-client-types-wasm",
	"forks/solana-account-decoder-wasm",
	"forks/solana-transaction-status-client-types-wasm",
	"forks/solana-transaction-status-wasm",
]
resolver = "2"

[workspace.package]
version = "0.11.0"
authors = ["Ifiok Jr. <ifiokotung@gmail.com>"]
edition = "2024"
homepage = "https://github.com/ifiokjr/wasm_solana"
license = "Unlicense"
repository = "https://github.com/ifiokjr/wasm_solana"
rust-version = "1.89.0"

[workspace.dependencies]
Inflector = { default-features = false, version = "^0.11" }
agave-reserved-account-keys = { default-features = false, features = ["agave-unstable-api"], version = "^4.2" }
anyhow = { default-features = false, version = "^1" }
assert2 = { default-features = false, version = "^0.3" }
assert_matches = { default-features = false, version = "^1" }
async-trait = { default-features = false, version = "^0.1" }
async-tungstenite = { default-features = false, version = "^0.28.1" }
base64 = { default-features = false, version = "^0.22" }
bincode = { default-features = false, version = "^1" }
borsh = { default-features = false, version = "^1" }
bs58 = { default-features = false, version = "^0.5" }
bv = { default-features = false, version = "^0.11" }
bytemuck = { default-features = false, version = "^1" }
cfg-if = { default-features = false, version = "^1" }
chrono-humanize = { default-features = false, version = "^0.2" }
crossbeam-channel = { default-features = false, version = "^0.5" }
derive_more = { default-features = false, version = "^2" }
fork_stream = { default-features = false, version = "^0.1" }
futures = { default-features = false, version = "^0.3" }
futures-timeout = { default-features = false, version = "^0.1" }
futures-timer = { default-features = false, version = "^3" }
getrandom = { default-features = false, version = "^0.3" }
gloo-net = { default-features = false, version = "^0.6" }
heck = { default-features = false, version = "^0.5" }
indexmap = { default-features = false, version = "^2" }
insta = { default-features = false, version = "^1" }
js-sys = { default-features = false, version = "^0.3" }
log = { default-features = false, version = "^0.4" }
nacl = { default-features = false, version = "^0.5" }
paste = { default-features = false, version = "^1" }
pin-project = { default-features = false, version = "^1" }
port_check = { default-features = false, version = "^0.3" }
rand = { default-features = false, version = "^0.9" }
regex = { default-features = false, version = "^1" }
reqwest = { default-features = false, version = "^0.12" }
reqwest-websocket = { default-features = false, version = "^0.5" }
semver = { default-features = false, version = "^1" }
send_wrapper = { default-features = false, version = "^0.6" }
serde = { default-features = false, features = ["derive"], version = "^1" }
serde-wasm-bindgen = { default-features = false, version = "^0.6" }
serde_bytes = { default-features = false, version = "^0.11" }
serde_derive = { default-features = false, version = "^1" }
serde_json = { default-features = false, version = "^1" }
serde_tuple = { default-features = false, version = "^1" }
serde_with = { default-features = false, version = "^3" }
solana-account = { default-features = false, version = ">=4.3.1, <4.4.0" }
solana-address-lookup-table-interface = { default-features = false, version = ">=3.1.0, <3.2.0" }
solana-banks-client = { features = ["agave-unstable-api"], default-features = false, version = "^4.2" }
solana-banks-interface = { features = ["agave-unstable-api"], default-features = false, version = "^4.2" }
solana-clock = { default-features = false, features = ["serde"], version = ">=3.0.1, <3.2.0" }
solana-commitment-config = { default-features = false, features = ["serde"], version = "^3.1" }
solana-compute-budget = { features = ["agave-unstable-api"], default-features = false, version = "=4.2.0" }
solana-compute-budget-interface = { default-features = false, features = ["borsh", "serde"], version = "^3" }
solana-config-interface = { default-features = false, features = ["bincode", "serde"], version = "^2" }
solana-epoch-info = { default-features = false, features = ["serde"], version = "^3.1" }
solana-epoch-schedule = { default-features = false, features = ["serde"], version = ">=3.2.0, <3.3.0" }
solana-faucet = { features = ["agave-unstable-api"], default-features = false, version = "^4.2" }
solana-fee-calculator = { default-features = false, features = ["serde"], version = ">=3.2.2, <3.3.0" }
solana-hash = { default-features = false, features = ["borsh", "bytemuck", "serde"], version = ">=4.4.0, <4.6.0" }
solana-inflation = { default-features = false, features = ["serde"], version = ">=3.1.1, <3.2.0" }
solana-instruction = { default-features = false, features = ["bincode", "borsh", "serde"], version = ">=3.4.0, <3.5.0" }
solana-keypair = { default-features = false, version = "^3.1" }
solana-loader-v2-interface = { default-features = false, features = ["bincode", "serde"], version = "^3" }
solana-loader-v3-interface = { default-features = false, features = ["serde"], version = "^7" }
solana-message = { default-features = false, features = ["serde"], version = ">=4.2.3, <4.5.0" }
solana-native-token = { default-features = false, version = "^3" }
solana-nonce = { default-features = false, features = ["serde"], version = ">=3.2.0, <3.3.0" }
solana-program-binaries = { default-features = false, version = "^4.2" }
solana-program-error = { default-features = false, features = ["borsh", "serde"], version = "^3" }
solana-program-option = { default-features = false, version = "^3.1" }
solana-program-pack = { default-features = false, version = "^3.1" }
solana-program-runtime = { features = ["agave-unstable-api"], default-features = false, version = "^4.2" }
solana-program-test = { features = ["agave-unstable-api"], default-features = false, version = "^4.2" }
solana-pubkey = { default-features = false, features = ["bytemuck", "borsh", "serde"], version = ">=4.2.0, <4.3.0" }
solana-rent = { default-features = false, features = ["serde"], version = ">=4.2.1, <4.4.0" }
solana-reward-info = { default-features = false, features = ["serde"], version = ">=6.2.0, <6.3.0" }
solana-rpc = { features = ["agave-unstable-api"], default-features = false, version = "^4.2" }
solana-sdk-ids = { default-features = false, version = "^3.1" }
solana-signature = { default-features = false, features = ["bytemuck", "serde", "verify"], version = ">=3.4.1, <3.5.0" }
solana-signer = { default-features = false, version = "^3" }
solana-slot-hashes = { default-features = false, features = ["serde"], version = ">=3.1.0, <3.2.0" }
solana-slot-history = { default-features = false, features = ["serde"], version = ">=3.0.1, <3.2.0" }
solana-stake-interface = { default-features = false, features = ["bincode", "borsh", "serde"], version = ">=4.3.0, <4.3.1" }
solana-system-interface = { default-features = false, features = ["bincode", "serde"], version = ">=3.2.0, <3.3.0" }
solana-system-program = { features = ["agave-unstable-api"], default-features = false, version = "^4.2" }
solana-sysvar = { default-features = false, features = ["bincode", "bytemuck", "serde"], version = ">=4.0.0, <4.2.0" }
solana-test-validator = { features = ["agave-unstable-api"], default-features = false, version = "^4.2" }
solana-transaction = { default-features = false, features = ["serde"], version = ">=4.1.4, <4.2.0" }
solana-transaction-context = { default-features = false, features = ["agave-unstable-api", "bincode", "serde"], version = "^4.2" }
solana-transaction-error = { default-features = false, features = ["serde"], version = ">=3.3.1, <3.4.0" }
solana-version = { features = ["agave-unstable-api"], default-features = false, version = "^4.2" }
solana-vote-interface = { default-features = false, version = ">=6.0.2, <6.1.0" }
solana-zk-sdk-pod = { default-features = false, version = "^0.1" }
solana-zk-token-sdk = { default-features = false, version = "^3.1" }
spl-associated-token-account-interface = { default-features = false, version = "^2" }
spl-generic-token = { default-features = false, version = "^2" }
spl-memo-interface = { default-features = false, version = "^2.1" }
spl-pod = { default-features = false, version = "^0.7" }
spl-token-2022-interface = { default-features = false, version = "^3.1" }
spl-token-confidential-transfer-proof-extraction = { default-features = false, version = "^0.6" }
spl-token-group-interface = { default-features = false, version = "^0.7" }
spl-token-interface = { default-features = false, version = "^3" }
spl-token-metadata-interface = { default-features = false, version = "^1" }
tarpc = { default-features = false, version = "^0.29" }
tempfile = { default-features = false, version = "^3" }
test-case = { default-features = false, version = "^3" }
test-log = { default-features = false, version = "^0.2" }
thiserror = { default-features = false, version = "^2" }
tokio = { default-features = false, version = "^1" }
typed-builder = { default-features = false, version = "^0.23" }
wallet_standard = { default-features = false, version = "^0.6" }
wasm-bindgen = { default-features = false, version = "^0.2" }
wasm-bindgen-futures = { default-features = false, version = "^0.4" }
wasm-bindgen-test = { default-features = false, version = "^0.3" }
web-sys = { default-features = false, version = "^0.3" }
wincode = { default-features = false, version = "^0.5" }
zstd = { version = "0.13", default-features = false }

solana-blake3-hasher = { default-features = false, version = "^3.1" }
solana-epoch-rewards-hasher = { default-features = false, version = "^3.1" }
solana-keccak-hasher = { default-features = false, version = "^3.1" }

# publishable crates
memory_wallet = { path = "crates/memory_wallet", version = "0.11.0" }
test_utils_insta = { path = "crates/test_utils_insta", version = "0.11.0" }
test_utils_keypairs = { path = "crates/test_utils_keypairs", version = "0.11.0" }
test_utils_solana = { path = "crates/test_utils_solana", version = "0.11.0" }
wasm_client_solana = { path = "crates/wasm_client_solana", version = "0.11.0" }

# forks
solana-account-decoder-client-types-wasm = { path = "forks/solana-account-decoder-client-types-wasm", version = "4.0.0" }
solana-account-decoder-wasm = { path = "forks/solana-account-decoder-wasm", version = "4.0.0" }
solana-transaction-status-client-types-wasm = { path = "forks/solana-transaction-status-client-types-wasm", version = "4.0.0" }
solana-transaction-status-wasm = { path = "forks/solana-transaction-status-wasm", version = "4.0.0" }

[workspace.metadata.bin]
cargo-llvm-cov = { version = "0.9.1" }
cargo-nextest = { version = "0.9.143" }
cargo-semver-checks = { version = "0.50.0" }
wait-for-them = { version = "0.5.1", bins = ["wait-for-them"] }
wasm-bindgen-cli = { version = "0.2.128", bins = ["wasm-bindgen", "wasm-bindgen-test-runner"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[profile.release]
lto = "fat"
overflow-checks = true

[workspace.lints.rust]
# Group lints
rust_2021_compatibility = { level = "warn", priority = -1 }
rust_2024_compatibility = { level = "warn", priority = -1 }

# Individual lints
unsafe_code = "deny"
unstable_features = "deny"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
unused_qualifications = "warn"
variant_size_differences = "warn"
edition_2024_expr_fragment_specifier = "allow"

[workspace.lints.clippy]
# Group lints
complexity = { level = "warn", priority = -1 }
correctness = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }

# Individual lints
blocks_in_conditions = "allow"
cargo_common_metadata = "allow"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
expl_impl_clone_on_copy = "allow"
items_after_statements = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
no_effect_underscore_binding = "allow"
tabs-in-doc-comments = "allow"
too_many_lines = "allow"
wildcard_dependencies = "deny"
wildcard_imports = "allow"
