[toolchain]
# https://rust-lang.github.io/rustup-components-history/
channel = "nightly-2025-01-03"
components = ["rustfmt", "cargo", "clippy", "rust-analyzer", "llvm-tools-preview"]
profile = "default"
targets = ["wasm32-unknown-unknown"]
