[toolchain]
# https://rust-lang.github.io/rustup-components-history/
channel = "nightly-2024-10-01"
components = ["rustfmt", "cargo", "clippy", "rust-analyzer", "llvm-tools-preview"]
profile = "default"
targets = ["wasm32-unknown-unknown"]
