[formatting]
indent_string = "\t"
column_width = 100
allowed_blank_lines = 1

[[rule]]
include = ["**/Cargo.toml", "Cargo.toml"]
keys = ["dependencies", "workspace.dependencies", "workspace.metadata.bin"]

[rule.formatting]
reorder_keys = true
